---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: gateway-auth-policy
  namespace: openshift-ingress
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
  rules:
    metadata:
      # API Key Validation
      apiKeyValidation:
        priority: 0
        http:
          url: https://maas-api.opendatahub.svc.cluster.local:8443/internal/v1/api-keys/validate
          contentType: application/json
          method: POST
          body:
            expression: '{"key": request.headers.authorization.replace("Bearer ", "")}'

      # Tier lookup
      matchedTier:
        priority: 0
        http:
          url: https://maas-api.opendatahub.svc.cluster.local:8443/v1/tiers/lookup
          contentType: application/json
          method: POST
          body:
            expression: '{"groups": auth.metadata.apiKeyValidation.groups}'
        cache:
          key:
            selector: auth.metadata.apiKeyValidation.username
          ttl: 300

    authentication:
      # API Keys - plain auth, real validation in metadata layer
      authentication:
        plain:
          selector: request.headers.authorization

    authorization:
      # Validate API key is valid
      api-key-valid:
        priority: 0
        patternMatching:
          patterns:
            - selector: auth.metadata.apiKeyValidation.valid
              operator: eq
              value: "true"

      # Tier-based access control
      tier-access:
        priority: 0
        when:
          # Only apply to inference paths (exclude API management)
          - selector: request.path
            operator: matches
            value: "^/(?!v1/|maas-api/)[^/]+/[^/]+(/.*)?$"
        cache:
          key:
            selector: auth.metadata.apiKeyValidation.username
          ttl: 60
        kubernetesSubjectAccessReview:
          user:
            selector: auth.metadata.apiKeyValidation.username
          authorizationGroups:
            selector: auth.metadata.apiKeyValidation.groups
          resourceAttributes:
            group:
              value: serving.kserve.io
            resource:
              value: llminferenceservices
            namespace:
              expression: request.path.split("/")[1]
            name:
              expression: request.path.split("/")[2]
            verb:
              value: post

    response:
      success:
        headers:
          # Username from API key validation
          X-MaaS-Username:
            plain:
              selector: auth.metadata.apiKeyValidation.username

          # Groups - construct JSON array string
          X-MaaS-Group:
            plain:
              expression: '["' + auth.metadata.apiKeyValidation.groups.join('","') + '"]'

          # Key ID
          X-MaaS-Key-Id:
            plain:
              selector: auth.metadata.apiKeyValidation.keyId

        filters:
          identity:
            priority: 0
            json:
              properties:
                userid:
                  selector: auth.metadata.apiKeyValidation.userId
                tier:
                  selector: auth.metadata.matchedTier.tier
