apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: simulator-access
  namespace: opendatahub
spec:
  modelRefs:
    - facebook-opt-125m-simulated
  subjects:
    groups:
      - name: system:authenticated
    users: []
