// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveKeysByUser = `-- name: CountActiveKeysByUser :one
SELECT COUNT(*) as count
FROM api_keys
WHERE username = $1 AND status = 'active'
`

func (q *Queries) CountActiveKeysByUser(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveKeysByUser, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec

INSERT INTO api_keys (
    id, username, name, description, key_hash, status, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateAPIKeyParams struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	KeyHash     string             `json:"key_hash"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// API Key Management Queries
// These queries are processed by sqlc to generate type-safe Go code in ../../internal/db/
// Generated files: db.go, models.go, queries.sql.go (excluded from git, see .gitignore)
// Run `make sqlc-generate` after modifying this file
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.Username,
		arg.Name,
		arg.Description,
		arg.KeyHash,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, username, name, description, status, last_used_at
FROM api_keys
WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

// Critical path: called on every authenticated request via Authorino
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, username, name, description, status, created_at, expires_at, last_used_at
FROM api_keys
WHERE id = $1
`

type GetAPIKeyByIDRow struct {
	ID          string             `json:"id"`
	Username    string             `json:"username"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getStaleKeys = `-- name: GetStaleKeys :many
SELECT id, username, name, created_at, last_used_at
FROM api_keys
WHERE status = 'active'
  AND (last_used_at IS NULL OR last_used_at < $1)
`

type GetStaleKeysRow struct {
	ID         string             `json:"id"`
	Username   string             `json:"username"`
	Name       string             `json:"name"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

// Find keys not used in the specified interval (for cleanup/audit)
func (q *Queries) GetStaleKeys(ctx context.Context, lastUsedAt pgtype.Timestamptz) ([]GetStaleKeysRow, error) {
	rows, err := q.db.Query(ctx, getStaleKeys, lastUsedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStaleKeysRow{}
	for rows.Next() {
		var i GetStaleKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, description, status, created_at, expires_at, last_used_at
FROM api_keys
WHERE username = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   time.Time          `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, username string) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys
SET status = 'revoked'
WHERE id = $1 AND status = 'active'
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllUserKeys = `-- name: RevokeAllUserKeys :execrows
UPDATE api_keys
SET status = 'revoked'
WHERE username = $1 AND status = 'active'
`

func (q *Queries) RevokeAllUserKeys(ctx context.Context, username string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserKeys, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLastUsed = `-- name: UpdateLastUsed :exec
UPDATE api_keys
SET last_used_at = $1
WHERE id = $2
`

type UpdateLastUsedParams struct {
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ID         string             `json:"id"`
}

func (q *Queries) UpdateLastUsed(ctx context.Context, arg UpdateLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
