apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../odh
  - platform-auth.yaml

configMapGenerator:
- behavior: merge
  envs:
  - params.env
  name: maas-parameters
generatorOptions:
  disableNameSuffixHash: true

replacements:
- source:
    kind: ConfigMap
    version: v1
    name: maas-parameters
    fieldPath: data.oidc-issuer-url
  targets:
  - select:
      kind: MaaSPlatformAuth
      name: platform-auth
    fieldPaths:
    - spec.externalOIDC.issuerUrl
- source:
    kind: ConfigMap
    version: v1
    name: maas-parameters
    fieldPath: data.oidc-client-id
  targets:
  - select:
      kind: MaaSPlatformAuth
      name: platform-auth
    fieldPaths:
    - spec.externalOIDC.clientId
