# MaaSAuthPolicy for the regular simulator: any authenticated user (system:authenticated).
# Paired with maas-subscription-regular.yaml for token rate limits.
apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSAuthPolicy
metadata:
  name: simulator-access
  namespace: models-as-a-service
spec:
  modelRefs:
    - facebook-opt-125m-simulated
  subjects:
    groups:
      - name: system:authenticated
    users: []
