/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package maas

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/go-logr/logr"
	kservev1alpha2 "github.com/kserve/kserve/pkg/apis/serving/v1alpha2"
	llmdv1alpha2 "github.com/llm-d/llm-d-router/apix/v1alpha2"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/equality"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	apimeta "k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/types"
	"knative.dev/pkg/kmeta"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"

	maasv1alpha1 "github.com/opendatahub-io/models-as-a-service/maas-controller/api/maas/v1alpha1"
	"github.com/opendatahub-io/models-as-a-service/maas-controller/pkg/oteljson"
	"github.com/opendatahub-io/models-as-a-service/maas-controller/pkg/platform/tenantreconcile"
)

const (
	// inferenceObjectiveNameMaxLength is the longest generated InferenceObjective name, the
	// limit kmeta.ChildName enforces.
	inferenceObjectiveNameMaxLength = 63
	inferenceObjectiveNamePrefix    = "maas"
	// inferenceObjectiveNameHashLength is the number of hex characters of the identity
	// hash kept in generated names. It is never truncated.
	inferenceObjectiveNameHashLength = 10

	inferenceObjectiveCRD = "inferenceobjectives.llm-d.ai"

	defaultInferencePoolGroup = "inference.networking.k8s.io"
	defaultInferencePoolKind  = "InferencePool"

	// Ownership metadata on generated InferenceObjectives. The subscription name and tenant
	// name are annotations because they are not guaranteed to fit in a label value; the
	// tenant key also differs from tenantreconcile.LabelTenantName, which marks
	// AITenant-managed resources.
	labelSubscriptionNamespace       = "maas.opendatahub.io/subscription-namespace"
	labelSubscriptionUID             = "maas.opendatahub.io/subscription-uid"
	annotationSubscriptionName       = "maas.opendatahub.io/subscription-name"
	annotationInferenceObjTenantName = "maas.opendatahub.io/tenant-name"
	inferenceObjectiveComponent      = "inference-objective"

	// inferenceObjectiveConflictRequeue rechecks a name held by a foreign object. The
	// InferenceObjective watch only sees objects carrying our labels.
	inferenceObjectiveConflictRequeue = 5 * time.Minute

	eventReasonInferenceObjectiveConflict = "InferenceObjectiveConflict"
	eventReasonInferenceObjectiveFailed   = "InferenceObjectiveFailed"
	eventReasonInferencePoolUnsupported   = "InferencePoolUnsupported"
	eventReasonInferencePoolNotOnGateway  = "InferencePoolNotOnTenantGateway"
)

// inferenceObjectiveOwnerLabels are the labels every generated InferenceObjective carries.
func inferenceObjectiveOwnerLabels() map[string]string {
	return map[string]string{
		"app.kubernetes.io/managed-by": "maas-controller",
		"app.kubernetes.io/part-of":    "maas-subscription",
		"app.kubernetes.io/component":  inferenceObjectiveComponent,
	}
}

// hasInferenceObjectiveOwnerLabels reports whether labels mark an InferenceObjective as
// generated by this controller.
func hasInferenceObjectiveOwnerLabels(labels map[string]string) bool {
	for k, v := range inferenceObjectiveOwnerLabels() {
		if labels[k] != v {
			return false
		}
	}
	return true
}

// inferenceObjectiveName returns the deterministic InferenceObjective name for a
// subscription and InferencePool: "maas-<tenant>-<subscription>-<pool>-<hash>". The hash
// of the full identities keeps names unique; kmeta.ChildName keeps it as the suffix and,
// when the name is too long, truncates the readable part. The name does not depend on
// spec.inferencePriority, so it is stable across priority changes. It also excludes the
// pool's API group and kind: KServe keeps the pool name stable but reports the group of
// whichever pool API version the gateway currently accepts.
func inferenceObjectiveName(tenantName string, subscription, pool types.NamespacedName) string {
	identity := strings.Join([]string{
		tenantName,
		subscription.Namespace, subscription.Name,
		pool.Namespace, pool.Name,
	}, "\x00")
	sum := sha256.Sum256([]byte(identity))
	hash := hex.EncodeToString(sum[:])[:inferenceObjectiveNameHashLength]

	// The tenant, subscription, and pool names are Kubernetes object names, so the joined
	// string is already a valid name. ChildName alone hashes only names that are too long,
	// so short names would collide (tenant "a-b" + subscription "c" vs tenant "a" +
	// subscription "b-c"), and the subscription namespace is not in the readable part. The
	// identity hash covers both.
	parent := strings.Join([]string{inferenceObjectiveNamePrefix, tenantName, subscription.Name, pool.Name}, "-")
	return kmeta.ChildName(parent, "-"+hash)
}

// flowControlTenantName returns the AITenant name for a subscription namespace. It falls
// back to the default tenant name when the namespace has no tenant config.
func flowControlTenantName(ctx context.Context, c client.Reader, namespace string) (string, error) {
	tenant, err := fetchTenantForNamespace(ctx, c, namespace)
	if err != nil {
		if apierrors.IsNotFound(err) || apimeta.IsNoMatchError(err) {
			return tenantreconcile.TenantNameFor(nil)
		}
		return "", err
	}
	return tenant.name()
}

// inferencePoolRef is the InferencePool an InferenceObjective points at. The pool is
// always in the objective's namespace.
type inferencePoolRef struct {
	Group string
	Kind  string
	Name  string
}

// poolResolutionReason explains why resolveModelInferencePool returned no pool.
type poolResolutionReason string

const (
	// poolResolutionPending: the pool is not observed yet; a watch re-triggers reconcile.
	poolResolutionPending poolResolutionReason = "Pending"
	// poolResolutionNotApplicable: the model is not served through an inference scheduler.
	poolResolutionNotApplicable poolResolutionReason = "NotApplicable"
	// poolResolutionUnsupported: the model has a scheduler topology objectives cannot target.
	poolResolutionUnsupported poolResolutionReason = "Unsupported"
)

// modelPoolResolution is the result of resolveModelInferencePool. Pool is set when the
// model has a single observed pool; otherwise Reason and Message explain why not.
type modelPoolResolution struct {
	Pool    *inferencePoolRef
	Reason  poolResolutionReason
	Message string
}

// resolveModelInferencePool returns the InferencePool observed for a MaaSModelRef. The pool
// lives in the model's namespace, alongside its LLMInferenceService. A non-nil error is a
// transient lookup failure that should be retried; missing resources are reported as
// Pending without an error because the MaaSModelRef and LLMInferenceService watches
// re-trigger reconciliation.
func (r *MaaSSubscriptionReconciler) resolveModelInferencePool(ctx context.Context, modelNamespace, modelName string) (modelPoolResolution, error) {
	model := &maasv1alpha1.MaaSModelRef{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: modelNamespace, Name: modelName}, model); err != nil {
		if apierrors.IsNotFound(err) {
			return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("MaaSModelRef %s/%s not found", modelNamespace, modelName)}, nil
		}
		return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("failed to get MaaSModelRef: %v", err)},
			fmt.Errorf("failed to get MaaSModelRef %s/%s: %w", modelNamespace, modelName, err)
	}
	if model.Spec.ModelRef.Kind != "LLMInferenceService" {
		return modelPoolResolution{
			Reason:  poolResolutionNotApplicable,
			Message: fmt.Sprintf("model kind %s is not served through an inference scheduler", model.Spec.ModelRef.Kind),
		}, nil
	}

	llmisvc := &kservev1alpha2.LLMInferenceService{}
	if err := r.Get(ctx, types.NamespacedName{Namespace: model.Namespace, Name: model.Spec.ModelRef.Name}, llmisvc); err != nil {
		if apierrors.IsNotFound(err) || apimeta.IsNoMatchError(err) {
			return modelPoolResolution{
				Reason:  poolResolutionPending,
				Message: fmt.Sprintf("LLMInferenceService %s/%s not found", model.Namespace, model.Spec.ModelRef.Name),
			}, nil
		}
		return modelPoolResolution{Reason: poolResolutionPending, Message: fmt.Sprintf("failed to get LLMInferenceService: %v", err)},
			fmt.Errorf("failed to get LLMInferenceService %s/%s: %w", model.Namespace, model.Spec.ModelRef.Name, err)
	}

	router := llmisvc.Status.Router
	if router != nil && router.Group != nil && activeRoutingGroupMembers(router.Group) > 1 {
		return modelPoolResolution{
			Reason: poolResolutionUnsupported,
			Message: fmt.Sprintf("LLMInferenceService %s/%s splits traffic across routing group %s; request priority requires a single InferencePool",
				llmisvc.Namespace, llmisvc.Name, router.Group.Name),
		}, nil
	}
	if router != nil && router.Scheduler != nil && router.Scheduler.InferencePool != nil {
		observed := router.Scheduler.InferencePool
		// An InferenceObjective can only reference a pool in its own namespace, and KServe
		// creates or references pools in the LLMInferenceService namespace.
		if observed.Namespace != nil && *observed.Namespace != "" && string(*observed.Namespace) != llmisvc.Namespace {
			return modelPoolResolution{
				Reason: poolResolutionUnsupported,
				Message: fmt.Sprintf("InferencePool %s/%s is not in the LLMInferenceService namespace %s",
					*observed.Namespace, observed.Name, llmisvc.Namespace),
			}, nil
		}
		pool := &inferencePoolRef{
			Group: string(observed.Group),
			Kind:  string(observed.Kind),
			Name:  string(observed.Name),
		}
		if pool.Group == "" {
			pool.Group = defaultInferencePoolGroup
		}
		if pool.Kind == "" {
			pool.Kind = defaultInferencePoolKind
		}
		return modelPoolResolution{Pool: pool}, nil
	}

	// The scheduler can come from the service spec or from a referenced config, so rely on
	// the observed status: a ready service without a pool is served without a scheduler.
	if llmisvcReadyStatus(llmisvc) != string(corev1.ConditionTrue) {
		return modelPoolResolution{
			Reason:  poolResolutionPending,
			Message: fmt.Sprintf("waiting for LLMInferenceService %s/%s to report an InferencePool", llmisvc.Namespace, llmisvc.Name),
		}, nil
	}
	return modelPoolResolution{
		Reason:  poolResolutionNotApplicable,
		Message: fmt.Sprintf("LLMInferenceService %s/%s is not served through an inference scheduler", llmisvc.Namespace, llmisvc.Name),
	}, nil
}

// activeRoutingGroupMembers counts routing group members that receive traffic.
func activeRoutingGroupMembers(group *kservev1alpha2.GroupStatus) int {
	active := 0
	for _, m := range group.Members {
		if !m.Stopped && m.Weight > 0 {
			active++
		}
	}
	return active
}

// desiredObjective is one InferenceObjective a subscription needs: one per InferencePool,
// shared by every referenced model served from that pool.
type desiredObjective struct {
	Pool       inferencePoolRef
	TenantName string
	Priority   int32
	// Models are the "namespace/name" model refs served from Pool, for logs and events.
	Models []string
}

// modelFlowControl is the request-priority state of one referenced model. Objective is the
// key of the model's InferenceObjective; it is zero when no objective name could be derived.
type modelFlowControl struct {
	Status    maasv1alpha1.ModelFlowControlStatus
	Objective types.NamespacedName
}

// flowControlMessageMaxLen is the schema maxLength of ModelFlowControlStatus.Message.
const flowControlMessageMaxLen = 1024

// setReason sets the model's reason and message, and derives Ready from the reason.
func (m *modelFlowControl) setReason(reason maasv1alpha1.FlowControlReason, message string) {
	m.Status.Reason = reason
	m.Status.Message = truncateMessage(message, flowControlMessageMaxLen)
	m.Status.Ready = flowControlReasonReady(reason)
}

// flowControlReasonReady reports whether a reason leaves nothing to reconcile for the model.
func flowControlReasonReady(reason maasv1alpha1.FlowControlReason) bool {
	switch reason {
	case maasv1alpha1.FlowControlReasonObjectiveReconciled,
		maasv1alpha1.FlowControlReasonPriorityUnset,
		maasv1alpha1.FlowControlReasonNotApplicable,
		maasv1alpha1.FlowControlReasonUnmanaged:
		return true
	default:
		return false
	}
}

// flowControlResolution is the result of resolveFlowControl.
type flowControlResolution struct {
	// Models has one entry per distinct model ref, sorted by namespace and name.
	Models []*modelFlowControl
	// Desired are the needed InferenceObjectives; empty when spec.inferencePriority is unset.
	Desired map[types.NamespacedName]*desiredObjective
	// Complete is false when a lookup failed; nothing is deleted then.
	Complete bool
}

// resolveFlowControl resolves each model's InferencePool and InferenceObjective name, and
// the objectives the subscription needs. Names are resolved even when
// spec.inferencePriority is unset. Failures are returned for retry.
func (r *MaaSSubscriptionReconciler) resolveFlowControl(ctx context.Context, sub *maasv1alpha1.MaaSSubscription) (flowControlResolution, error) {
	res := flowControlResolution{Desired: make(map[types.NamespacedName]*desiredObjective), Complete: true}
	prioritySet := sub.Spec.InferencePriority != nil
	// warnf records events only when request priority is set.
	warnf := func(reason, messageFmt string, args ...any) {
		if prioritySet {
			r.warnf(sub, reason, messageFmt, args...)
		}
	}

	refs := make([]string, 0, len(sub.Spec.ModelRefs))
	for _, ref := range sub.Spec.ModelRefs {
		key := ref.Namespace + "/" + ref.Name
		if !slices.Contains(refs, key) {
			refs = append(refs, key)
		}
	}
	slices.Sort(refs)

	var errs []error
	// fail marks a model as failed for a transient error that is returned for retry.
	fail := func(m *modelFlowControl, err error) {
		res.Complete = false
		errs = append(errs, err)
		m.setReason(maasv1alpha1.FlowControlReasonReconcileFailed, err.Error())
	}

	// Resolved once, on first use. A failure is set on every model that needs it.
	var (
		gatewayRef      maasv1alpha1.TenantGatewayRef
		gatewayErr      error
		gatewayResolved bool
		tenantName      string
		tenantErr       error
		tenantResolved  bool
	)

	for _, key := range refs {
		modelNamespace, modelName, _ := strings.Cut(key, "/")
		m := &modelFlowControl{Status: maasv1alpha1.ModelFlowControlStatus{Name: modelName, Namespace: modelNamespace}}
		res.Models = append(res.Models, m)

		pool, err := r.resolveModelInferencePool(ctx, modelNamespace, modelName)
		if err != nil {
			fail(m, fmt.Errorf("model %s: %w", key, err))
			continue
		}
		if pool.Pool == nil {
			switch pool.Reason {
			case poolResolutionPending:
				m.setReason(maasv1alpha1.FlowControlReasonPoolPending, pool.Message)
			case poolResolutionNotApplicable:
				m.setReason(maasv1alpha1.FlowControlReasonNotApplicable, pool.Message)
			case poolResolutionUnsupported:
				m.setReason(maasv1alpha1.FlowControlReasonUnsupported, pool.Message)
				warnf(eventReasonInferencePoolUnsupported, "Request priority is not applied to model %s: %s", key, pool.Message)
			}
			continue
		}
		m.Status.InferencePool = &gatewayapiv1.LocalObjectReference{
			Group: gatewayapiv1.Group(pool.Pool.Group),
			Kind:  gatewayapiv1.Kind(pool.Pool.Kind),
			Name:  gatewayapiv1.ObjectName(pool.Pool.Name),
		}

		if !gatewayResolved {
			gatewayRef, gatewayErr = tenantGatewayRefForNamespace(ctx, r.Client, sub.Namespace,
				r.DefaultTenantNamespace, r.GatewayName, r.GatewayNamespace, r.TenantNamespaceDiscoveryEnabled)
			if gatewayErr != nil {
				gatewayErr = fmt.Errorf("failed to resolve tenant gateway for namespace %s: %w", sub.Namespace, gatewayErr)
				warnf(eventReasonInferenceObjectiveFailed, "%v", gatewayErr)
				errs = append(errs, gatewayErr)
			}
			gatewayResolved = true
		}
		if gatewayErr != nil {
			res.Complete = false
			m.setReason(maasv1alpha1.FlowControlReasonReconcileFailed, gatewayErr.Error())
			continue
		}
		routeName, routeNamespace, err := findHTTPRouteForModel(ctx, r.Client, modelNamespace, modelName)
		if err == nil {
			err = validateHTTPRouteReferencesGateway(ctx, r.Client, routeName, routeNamespace, gatewayRef)
		}
		switch {
		case err == nil:
		case errors.Is(err, ErrModelNotFound), errors.Is(err, ErrHTTPRouteNotFound):
			m.setReason(maasv1alpha1.FlowControlReasonPoolPending, fmt.Sprintf("waiting for the HTTPRoute of model %s", key))
			continue
		case errors.Is(err, ErrHTTPRouteNotOnTenantGateway):
			m.setReason(maasv1alpha1.FlowControlReasonNotOnTenantGateway, err.Error())
			warnf(eventReasonInferencePoolNotOnGateway, "Request priority is not applied to model %s: %v", key, err)
			continue
		default:
			fail(m, fmt.Errorf("model %s: gateway check: %w", key, err))
			continue
		}

		if !tenantResolved {
			tenantName, tenantErr = flowControlTenantName(ctx, r.Client, sub.Namespace)
			if tenantErr != nil {
				tenantErr = fmt.Errorf("failed to resolve tenant for namespace %s: %w", sub.Namespace, tenantErr)
				warnf(eventReasonInferenceObjectiveFailed, "%v", tenantErr)
				errs = append(errs, tenantErr)
			}
			tenantResolved = true
		}
		if tenantErr != nil {
			res.Complete = false
			m.setReason(maasv1alpha1.FlowControlReasonReconcileFailed, tenantErr.Error())
			continue
		}

		m.Objective = types.NamespacedName{
			Namespace: modelNamespace,
			Name: inferenceObjectiveName(tenantName, client.ObjectKeyFromObject(sub),
				types.NamespacedName{Namespace: modelNamespace, Name: pool.Pool.Name}),
		}
		m.Status.ObjectiveName = m.Objective.Name
		if !prioritySet {
			m.setReason(maasv1alpha1.FlowControlReasonPriorityUnset,
				"inferencePriority is unset; no InferenceObjective is created and the scheduler applies priority 0")
			continue
		}
		// Pending until reconcileInferenceObjectives applies and observes the objective.
		m.setReason(maasv1alpha1.FlowControlReasonObjectivePending, "InferenceObjective is not reconciled yet")
		if d, ok := res.Desired[m.Objective]; ok {
			d.Models = append(d.Models, key)
			continue
		}
		res.Desired[m.Objective] = &desiredObjective{Pool: *pool.Pool, TenantName: tenantName, Priority: *sub.Spec.InferencePriority, Models: []string{key}}
	}
	if !prioritySet {
		// Nothing is desired, so cleanup is safe despite lookup errors.
		res.Complete = true
	}
	return res, errors.Join(errs...)
}

// inferenceObjectiveApplyOutcome is the result of applyInferenceObjective.
type inferenceObjectiveApplyOutcome int

const (
	inferenceObjectiveApplied inferenceObjectiveApplyOutcome = iota
	// inferenceObjectiveConflict: a foreign object holds the name; it is left untouched.
	inferenceObjectiveConflict
	// inferenceObjectiveAPIUnavailable: the InferenceObjective API is not served.
	inferenceObjectiveAPIUnavailable
)

// isAPIUnavailable reports whether err means the InferenceObjective API is not served.
func isAPIUnavailable(err error) bool {
	return apimeta.IsNoMatchError(err) || apierrors.IsNotFound(err)
}

// buildInferenceObjective returns the InferenceObjective for a desired entry.
func buildInferenceObjective(sub *maasv1alpha1.MaaSSubscription, key types.NamespacedName, d *desiredObjective) *llmdv1alpha2.InferenceObjective {
	labels := inferenceObjectiveOwnerLabels()
	labels[labelSubscriptionNamespace] = sub.Namespace
	labels[labelSubscriptionUID] = string(sub.UID)
	return &llmdv1alpha2.InferenceObjective{
		ObjectMeta: metav1.ObjectMeta{
			Name:      key.Name,
			Namespace: key.Namespace,
			Labels:    labels,
			Annotations: map[string]string{
				annotationSubscriptionName:       sub.Name,
				annotationInferenceObjTenantName: d.TenantName,
			},
		},
		Spec: inferenceObjectiveSpec(d),
	}
}

// inferenceObjectiveSpec returns the spec for a desired entry.
func inferenceObjectiveSpec(d *desiredObjective) llmdv1alpha2.InferenceObjectiveSpec {
	priority := d.Priority
	return llmdv1alpha2.InferenceObjectiveSpec{
		Priority: &priority,
		PoolRef: llmdv1alpha2.PoolObjectReference{
			Group: llmdv1alpha2.Group(d.Pool.Group),
			Kind:  llmdv1alpha2.Kind(d.Pool.Kind),
			Name:  llmdv1alpha2.ObjectName(d.Pool.Name),
		},
	}
}

// applyInferenceObjective creates or updates the InferenceObjective for one desired entry.
// It never touches an object it does not own or one that opted out of management.
func (r *MaaSSubscriptionReconciler) applyInferenceObjective(
	ctx context.Context,
	log logr.Logger,
	sub *maasv1alpha1.MaaSSubscription,
	key types.NamespacedName,
	d *desiredObjective,
) (inferenceObjectiveApplyOutcome, error) {
	log = log.WithValues("inferenceObjective", key.String(), "models", d.Models)
	desired := buildInferenceObjective(sub, key, d)

	existing := &llmdv1alpha2.InferenceObjective{}
	err := r.Get(ctx, key, existing)
	switch {
	case apimeta.IsNoMatchError(err):
		return inferenceObjectiveAPIUnavailable, nil
	case apierrors.IsNotFound(err):
		if err := r.Create(ctx, desired); err != nil {
			if isAPIUnavailable(err) {
				return inferenceObjectiveAPIUnavailable, nil
			}
			return inferenceObjectiveApplied, fmt.Errorf("failed to create InferenceObjective %s: %w", key, err)
		}
		log.Info("InferenceObjective created", "priority", d.Priority, "pool", d.Pool.Name)
		return inferenceObjectiveApplied, nil
	case err != nil:
		return inferenceObjectiveApplied, fmt.Errorf("failed to get InferenceObjective %s: %w", key, err)
	}

	if !existing.GetDeletionTimestamp().IsZero() {
		return inferenceObjectiveApplied, fmt.Errorf("InferenceObjective %s is being deleted; will recreate it", key)
	}
	labels := existing.GetLabels()
	if !hasInferenceObjectiveOwnerLabels(labels) {
		r.warnf(sub, eventReasonInferenceObjectiveConflict,
			"InferenceObjective %s already exists and is not managed by maas-controller; request priority is not applied to %s",
			key, strings.Join(d.Models, ", "))
		return inferenceObjectiveConflict, nil
	}
	if labels[labelSubscriptionNamespace] != sub.Namespace || existing.GetAnnotations()[annotationSubscriptionName] != sub.Name {
		r.warnf(sub, eventReasonInferenceObjectiveConflict,
			"InferenceObjective %s belongs to subscription %s/%s; request priority is not applied to %s",
			key, labels[labelSubscriptionNamespace], existing.GetAnnotations()[annotationSubscriptionName], strings.Join(d.Models, ", "))
		return inferenceObjectiveConflict, nil
	}
	if !isManaged(existing) {
		log.Info("InferenceObjective opted out, skipping update")
		return inferenceObjectiveApplied, nil
	}

	// Merge our metadata over the existing object. This also adopts an objective left by
	// an earlier subscription with the same name by rewriting the UID label.
	snapshot := existing.DeepCopy()
	maps.Copy(existing.Labels, desired.Labels)
	if existing.Annotations == nil {
		existing.Annotations = make(map[string]string)
	}
	maps.Copy(existing.Annotations, desired.Annotations)
	existing.Spec = desired.Spec

	if equality.Semantic.DeepEqual(snapshot.ObjectMeta, existing.ObjectMeta) && equality.Semantic.DeepEqual(snapshot.Spec, existing.Spec) {
		return inferenceObjectiveApplied, nil
	}
	if err := r.Update(ctx, existing); err != nil {
		return inferenceObjectiveApplied, fmt.Errorf("failed to update InferenceObjective %s: %w", key, err)
	}
	log.Info("InferenceObjective updated", "priority", d.Priority, "pool", d.Pool.Name,
		"adopted", snapshot.GetLabels()[labelSubscriptionUID] != string(sub.UID))
	return inferenceObjectiveApplied, nil
}

// inferenceObjectivesResult is the result of reconcileInferenceObjectives.
type inferenceObjectivesResult struct {
	// Statuses has one entry per distinct model ref, sorted by namespace and name.
	Statuses []maasv1alpha1.ModelFlowControlStatus
	// Conflict is true when a foreign object holds a needed name.
	Conflict bool
	// APIUnavailable is true when the InferenceObjective API is not served.
	APIUnavailable bool
}

// reconcileInferenceObjectives creates, updates, and deletes the subscription's
// InferenceObjectives and returns each model's status. A model is reconciled once its
// objective is observed with the desired spec. Obsolete objectives are deleted only when
// the desired set is complete. Errors are returned for retry.
func (r *MaaSSubscriptionReconciler) reconcileInferenceObjectives(ctx context.Context, log logr.Logger, sub *maasv1alpha1.MaaSSubscription) (result inferenceObjectivesResult, _ error) {
	res, err := r.resolveFlowControl(ctx, sub)
	var errs []error
	if err != nil {
		errs = append(errs, err)
	}
	// Statuses are copied out on every return, after the reasons are final.
	defer func() {
		result.Statuses = make([]maasv1alpha1.ModelFlowControlStatus, len(res.Models))
		for i, m := range res.Models {
			result.Statuses[i] = m.Status
		}
	}()

	// byObjective lists the models that need each desired objective.
	byObjective := make(map[types.NamespacedName][]*modelFlowControl, len(res.Desired))
	for _, m := range res.Models {
		if _, ok := res.Desired[m.Objective]; ok {
			byObjective[m.Objective] = append(byObjective[m.Objective], m)
		}
	}
	setObjectiveReason := func(key types.NamespacedName, reason maasv1alpha1.FlowControlReason, message string) {
		for _, m := range byObjective[key] {
			m.setReason(reason, message)
		}
	}
	apiUnavailable := func() (inferenceObjectivesResult, error) {
		log.V(1).Info("InferenceObjective API is not served; skipping request priority")
		result.APIUnavailable = true
		for key := range res.Desired {
			setObjectiveReason(key, maasv1alpha1.FlowControlReasonAPIUnavailable, "the InferenceObjective API (llm-d.ai) is not installed")
		}
		return result, errors.Join(errs...)
	}
	if r.inferenceObjectivesUnavailable.Load() {
		return apiUnavailable()
	}

	keys := slices.SortedFunc(maps.Keys(res.Desired), func(a, b types.NamespacedName) int {
		return strings.Compare(a.String(), b.String())
	})
	keep := make(map[types.NamespacedName]struct{}, len(res.Desired))
	// applied are the objectives to verify against the API server.
	applied := make([]types.NamespacedName, 0, len(keys))
	for _, key := range keys {
		keep[key] = struct{}{}
		outcome, applyErr := r.applyInferenceObjective(ctx, log, sub, key, res.Desired[key])
		switch {
		case outcome == inferenceObjectiveAPIUnavailable:
			return apiUnavailable()
		case outcome == inferenceObjectiveConflict:
			result.Conflict = true
			setObjectiveReason(key, maasv1alpha1.FlowControlReasonObjectiveConflict,
				fmt.Sprintf("InferenceObjective %s is held by an object not managed for this subscription", key))
		case applyErr != nil:
			errs = append(errs, applyErr)
			// AlreadyExists and Conflict mean a stale cache: pending, retried without a Warning.
			if apierrors.IsAlreadyExists(applyErr) || apierrors.IsConflict(applyErr) {
				setObjectiveReason(key, maasv1alpha1.FlowControlReasonObjectivePending, "InferenceObjective is not reconciled yet")
				continue
			}
			r.warnf(sub, eventReasonInferenceObjectiveFailed, "%v", applyErr)
			setObjectiveReason(key, maasv1alpha1.FlowControlReasonReconcileFailed, applyErr.Error())
		default:
			applied = append(applied, key)
		}
	}

	owned, err := r.listOwnedInferenceObjectives(ctx, sub)
	if err != nil {
		errs = append(errs, err)
		for _, key := range applied {
			setObjectiveReason(key, maasv1alpha1.FlowControlReasonReconcileFailed, err.Error())
		}
		return result, errors.Join(errs...)
	}
	observed := make(map[types.NamespacedName]*llmdv1alpha2.InferenceObjective, len(owned))
	for _, obj := range owned {
		observed[client.ObjectKeyFromObject(obj)] = obj
	}
	for _, key := range applied {
		reason, message := observedObjectiveReason(observed[key], res.Desired[key])
		setObjectiveReason(key, reason, message)
	}

	if res.Complete {
		if err := r.deleteInferenceObjectives(ctx, log, owned, keep); err != nil {
			errs = append(errs, err)
		}
	}
	return result, errors.Join(errs...)
}

// flowControlConditionReasons orders the reasons a model is not ready, most severe first.
// The InferenceObjectivesReady condition reports the most severe one.
var flowControlConditionReasons = []maasv1alpha1.FlowControlReason{
	maasv1alpha1.FlowControlReasonReconcileFailed,
	maasv1alpha1.FlowControlReasonObjectiveConflict,
	maasv1alpha1.FlowControlReasonNotOnTenantGateway,
	maasv1alpha1.FlowControlReasonUnsupported,
	maasv1alpha1.FlowControlReasonAPIUnavailable,
	maasv1alpha1.FlowControlReasonObjectivePending,
	maasv1alpha1.FlowControlReasonPoolPending,
}

// flowControlDegrades reports whether a reason caps the subscription phase at Degraded.
// Pending states and a missing InferenceObjective API do not.
func flowControlDegrades(reason maasv1alpha1.FlowControlReason) bool {
	switch reason {
	case maasv1alpha1.FlowControlReasonReconcileFailed,
		maasv1alpha1.FlowControlReasonObjectiveConflict,
		maasv1alpha1.FlowControlReasonNotOnTenantGateway,
		maasv1alpha1.FlowControlReasonUnsupported:
		return true
	default:
		return false
	}
}

// inferenceObjectivesCondition builds the InferenceObjectivesReady condition from the model
// statuses and reports whether they cap the phase at Degraded. ok is false when
// spec.inferencePriority is unset.
func inferenceObjectivesCondition(sub *maasv1alpha1.MaaSSubscription, statuses []maasv1alpha1.ModelFlowControlStatus) (cond metav1.Condition, degraded, ok bool) {
	if sub.Spec.InferencePriority == nil {
		return metav1.Condition{}, false, false
	}
	cond = metav1.Condition{
		Type:               maasv1alpha1.ConditionInferenceObjectivesReady,
		ObservedGeneration: sub.GetGeneration(),
	}
	var notReady []string
	worst := len(flowControlConditionReasons)
	for _, s := range statuses {
		if s.Ready {
			continue
		}
		notReady = append(notReady, fmt.Sprintf("%s/%s (%s)", s.Namespace, s.Name, s.Reason))
		if i := slices.Index(flowControlConditionReasons, s.Reason); i >= 0 && i < worst {
			worst = i
		}
		degraded = degraded || flowControlDegrades(s.Reason)
	}
	if len(notReady) == 0 {
		cond.Status = metav1.ConditionTrue
		cond.Reason = string(maasv1alpha1.ReasonReconciled)
		cond.Message = fmt.Sprintf("request priority is reconciled for all %d models", len(statuses))
		return cond, false, true
	}
	cond.Status = metav1.ConditionFalse
	cond.Reason = string(maasv1alpha1.FlowControlReasonReconcileFailed)
	if worst < len(flowControlConditionReasons) {
		cond.Reason = string(flowControlConditionReasons[worst])
	}
	cond.Message = truncateConditionMessage(fmt.Sprintf("request priority is not reconciled for %d of %d models: %s",
		len(notReady), len(statuses), strings.Join(notReady, ", ")))
	return cond, degraded, true
}

// observedObjectiveReason compares an objective read from the API server with the desired
// one. obj is nil when the objective was not observed.
func observedObjectiveReason(obj *llmdv1alpha2.InferenceObjective, d *desiredObjective) (maasv1alpha1.FlowControlReason, string) {
	switch {
	case obj == nil:
		return maasv1alpha1.FlowControlReasonObjectivePending, "InferenceObjective is not observed yet"
	case !isManaged(obj):
		priority := "unset"
		if obj.Spec.Priority != nil {
			priority = strconv.FormatInt(int64(*obj.Spec.Priority), 10)
		}
		return maasv1alpha1.FlowControlReasonUnmanaged,
			fmt.Sprintf("InferenceObjective opted out of management; its priority (%s) is owned by the user", priority)
	case !equality.Semantic.DeepEqual(obj.Spec, inferenceObjectiveSpec(d)):
		return maasv1alpha1.FlowControlReasonObjectivePending, "InferenceObjective does not match inferencePriority yet"
	default:
		return maasv1alpha1.FlowControlReasonObjectiveReconciled, fmt.Sprintf("InferenceObjective sets priority %d", d.Priority)
	}
}

// listOwnedInferenceObjectives lists the subscription's InferenceObjectives by ownership
// labels and annotation. It reads from the API server, since the cache can miss objectives
// created moments ago. It returns none when the API is not served.
func (r *MaaSSubscriptionReconciler) listOwnedInferenceObjectives(ctx context.Context, sub *maasv1alpha1.MaaSSubscription) ([]*llmdv1alpha2.InferenceObjective, error) {
	list := &llmdv1alpha2.InferenceObjectiveList{}
	selector := client.MatchingLabels(inferenceObjectiveOwnerLabels())
	selector[labelSubscriptionNamespace] = sub.Namespace
	if err := r.APIReader.List(ctx, list, selector); err != nil {
		if isAPIUnavailable(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to list InferenceObjectives for subscription %s/%s: %w", sub.Namespace, sub.Name, err)
	}
	var owned []*llmdv1alpha2.InferenceObjective
	for i := range list.Items {
		if list.Items[i].GetAnnotations()[annotationSubscriptionName] == sub.Name {
			owned = append(owned, &list.Items[i])
		}
	}
	return owned, nil
}

// deleteOwnedInferenceObjectives deletes all of the subscription's InferenceObjectives, for
// finalizer cleanup. Objectives that opted out of management are left in place.
func (r *MaaSSubscriptionReconciler) deleteOwnedInferenceObjectives(ctx context.Context, log logr.Logger, sub *maasv1alpha1.MaaSSubscription) error {
	owned, err := r.listOwnedInferenceObjectives(ctx, sub)
	if err != nil {
		return err
	}
	return r.deleteInferenceObjectives(ctx, log, owned, nil)
}

// deleteInferenceObjectives deletes the owned objectives that are not in keep. Objectives that
// opted out of management are left in place.
func (r *MaaSSubscriptionReconciler) deleteInferenceObjectives(ctx context.Context, log logr.Logger, owned []*llmdv1alpha2.InferenceObjective, keep map[types.NamespacedName]struct{}) error {
	var errs []error
	for _, obj := range owned {
		key := client.ObjectKeyFromObject(obj)
		if _, ok := keep[key]; ok {
			continue
		}
		if !isManaged(obj) {
			log.Info("InferenceObjective opted out, skipping deletion", "inferenceObjective", key.String())
			continue
		}
		uid := obj.GetUID()
		if err := r.Delete(ctx, obj, client.Preconditions{UID: &uid}); err != nil && !apierrors.IsNotFound(err) {
			errs = append(errs, fmt.Errorf("failed to delete InferenceObjective %s: %w", key, err))
			continue
		}
		log.Info("InferenceObjective deleted", "inferenceObjective", key.String())
	}
	return errors.Join(errs...)
}

// warnf records a Warning event on the subscription. SetupWithManager always sets Recorder.
func (r *MaaSSubscriptionReconciler) warnf(sub *maasv1alpha1.MaaSSubscription, reason, messageFmt string, args ...any) {
	r.Recorder.Eventf(sub, nil, corev1.EventTypeWarning, reason, "ReconcileInferenceObjectives", messageFmt, args...)
}

// mapLLMISvcToMaaSSubscriptions returns reconcile requests for the MaaSSubscriptions that
// reference MaaSModelRefs backed by the LLMInferenceService.
func (r *MaaSSubscriptionReconciler) mapLLMISvcToMaaSSubscriptions(ctx context.Context, obj client.Object) []reconcile.Request {
	var models maasv1alpha1.MaaSModelRefList
	if err := r.List(ctx, &models, client.InNamespace(obj.GetNamespace())); err != nil {
		oteljson.FromContext(ctx).Error(err, "failed to list MaaSModelRefs for LLMInferenceService", "llmisvc", qualifiedName(obj.GetNamespace(), obj.GetName()))
		return nil
	}
	seen := make(map[types.NamespacedName]struct{})
	var requests []reconcile.Request
	for i := range models.Items {
		m := &models.Items[i]
		if m.Spec.ModelRef.Kind != "LLMInferenceService" || m.Spec.ModelRef.Name != obj.GetName() {
			continue
		}
		for _, req := range r.mapMaaSModelRefToMaaSSubscriptions(ctx, m) {
			if _, ok := seen[req.NamespacedName]; ok {
				continue
			}
			seen[req.NamespacedName] = struct{}{}
			requests = append(requests, req)
		}
	}
	return requests
}

// llmisvcRouterStatusChangedPredicate passes Create/Delete events and Update events where the
// LLMInferenceService's observed router topology or Ready condition changed.
type llmisvcRouterStatusChangedPredicate struct {
	predicate.Funcs
}

func (llmisvcRouterStatusChangedPredicate) Update(e event.UpdateEvent) bool {
	if e.ObjectOld == nil || e.ObjectNew == nil {
		return true
	}
	if oldObj, ok := e.ObjectOld.(*kservev1alpha2.LLMInferenceService); ok {
		newObj, ok := e.ObjectNew.(*kservev1alpha2.LLMInferenceService)
		if !ok {
			return true
		}
		return !equality.Semantic.DeepEqual(oldObj.Status.Router, newObj.Status.Router) ||
			llmisvcReadyStatus(oldObj) != llmisvcReadyStatus(newObj)
	}
	// Dynamic watches registered after the CRD appears deliver unstructured objects.
	oldU, ok := e.ObjectOld.(*unstructured.Unstructured)
	if !ok {
		return true
	}
	newU, ok := e.ObjectNew.(*unstructured.Unstructured)
	if !ok {
		return true
	}
	oldRouter, _, _ := unstructured.NestedFieldNoCopy(oldU.Object, "status", "router")
	newRouter, _, _ := unstructured.NestedFieldNoCopy(newU.Object, "status", "router")
	return !equality.Semantic.DeepEqual(oldRouter, newRouter) ||
		unstructuredLLMIsvcReadyStatus(oldU) != unstructuredLLMIsvcReadyStatus(newU)
}

// mapInferenceObjectiveToSubscription maps a generated InferenceObjective to the
// subscription named by its ownership metadata.
func mapInferenceObjectiveToSubscription(_ context.Context, obj client.Object) []reconcile.Request {
	namespace := obj.GetLabels()[labelSubscriptionNamespace]
	name := obj.GetAnnotations()[annotationSubscriptionName]
	if namespace == "" || name == "" {
		return nil
	}
	return []reconcile.Request{{NamespacedName: types.NamespacedName{Namespace: namespace, Name: name}}}
}

// ownedInferenceObjectivePredicate passes events for InferenceObjectives generated by this
// controller. Create and Delete pass so a deleted objective is recreated; Update passes on
// spec, label, or annotation changes and drops status-only writes by the scheduler.
func ownedInferenceObjectivePredicate() predicate.Funcs {
	owned := func(obj client.Object) bool {
		return obj != nil && hasInferenceObjectiveOwnerLabels(obj.GetLabels())
	}
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool { return owned(e.Object) },
		DeleteFunc: func(e event.DeleteEvent) bool { return owned(e.Object) },
		UpdateFunc: func(e event.UpdateEvent) bool {
			if !owned(e.ObjectOld) && !owned(e.ObjectNew) {
				return false
			}
			if e.ObjectOld == nil || e.ObjectNew == nil {
				return true
			}
			return e.ObjectOld.GetGeneration() != e.ObjectNew.GetGeneration() ||
				!maps.Equal(e.ObjectOld.GetLabels(), e.ObjectNew.GetLabels()) ||
				!maps.Equal(e.ObjectOld.GetAnnotations(), e.ObjectNew.GetAnnotations())
		},
		GenericFunc: func(event.GenericEvent) bool { return false },
	}
}

// mapTenantConfigToMaaSSubscriptions enqueues the subscriptions in a MaasTenantConfig or
// legacy Tenant namespace. The tenant name and gateway are part of the objective's identity
// and placement, so a tenant change re-runs the InferenceObjective pass.
func (r *MaaSSubscriptionReconciler) mapTenantConfigToMaaSSubscriptions(ctx context.Context, obj client.Object) []reconcile.Request {
	subList := &maasv1alpha1.MaaSSubscriptionList{}
	if err := r.List(ctx, subList, client.InNamespace(obj.GetNamespace())); err != nil {
		oteljson.FromContext(ctx).Error(err, "failed to list MaaSSubscriptions for tenant config change",
			"tenantConfig", qualifiedName(obj.GetNamespace(), obj.GetName()))
		return nil
	}
	subList.Items = filterSubscriptionsByTenantNamespace(ctx, r.Client, subList.Items, r.DefaultTenantNamespace, r.TenantNamespaceDiscoveryEnabled)
	requests := make([]reconcile.Request, len(subList.Items))
	for i, sub := range subList.Items {
		requests[i] = reconcile.Request{NamespacedName: types.NamespacedName{Namespace: sub.Namespace, Name: sub.Name}}
	}
	return requests
}

// subscriptionsWithInferencePriority returns reconcile requests for every subscription that
// sets spec.inferencePriority. It runs when the InferenceObjective CRD appears; a list
// error is returned so the caller retries.
func (r *MaaSSubscriptionReconciler) subscriptionsWithInferencePriority(ctx context.Context) ([]reconcile.Request, error) {
	subList := &maasv1alpha1.MaaSSubscriptionList{}
	if err := r.List(ctx, subList); err != nil {
		return nil, fmt.Errorf("failed to list MaaSSubscriptions: %w", err)
	}
	subList.Items = filterSubscriptionsByTenantNamespace(ctx, r.Client, subList.Items, r.DefaultTenantNamespace, r.TenantNamespaceDiscoveryEnabled)
	var requests []reconcile.Request
	for _, sub := range subList.Items {
		if sub.Spec.InferencePriority != nil {
			requests = append(requests, reconcile.Request{NamespacedName: types.NamespacedName{Namespace: sub.Namespace, Name: sub.Name}})
		}
	}
	return requests, nil
}
