/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package maas

import (
	"context"
	"strings"
	"testing"

	"github.com/google/cel-go/cel"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	gatewayapiv1 "sigs.k8s.io/gateway-api/apis/v1"

	maasv1alpha1 "github.com/opendatahub-io/models-as-a-service/maas-controller/api/maas/v1alpha1"
)

// newPreexistingAuthPolicy builds a Kuadrant AuthPolicy as an unstructured object
// with a sentinel value in spec.targetRef.name. Tests use this to detect whether
// the controller overwrote the spec or left it untouched.
func newPreexistingAuthPolicy(name, namespace, modelName string, annotations map[string]string) *unstructured.Unstructured {
	ap := &unstructured.Unstructured{}
	ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	ap.SetName(name)
	ap.SetNamespace(namespace)
	ap.SetLabels(map[string]string{
		"maas.opendatahub.io/model":    modelName,
		"app.kubernetes.io/managed-by": "maas-controller",
		"app.kubernetes.io/part-of":    "maas-auth-policy",
		"app.kubernetes.io/component":  "auth-policy",
	})
	ap.SetAnnotations(annotations)
	_ = unstructured.SetNestedField(ap.Object, "sentinel-route", "spec", "targetRef", "name")
	return ap
}

// TestMaaSAuthPolicyReconciler_ManagedAnnotation verifies the opt-out behaviour of the
// "opendatahub.io/managed" annotation on generated Kuadrant AuthPolicy resources.
//
// When the annotation is set to "false" on an existing AuthPolicy, the controller must
// leave the resource untouched. Any other value (or the annotation being absent) means
// the controller owns the resource and must overwrite its spec.
func TestMaaSAuthPolicyReconciler_ManagedAnnotation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		httpRouteName  = "maas-model-" + modelName // ExternalModel naming convention
		authPolicyName = "maas-auth-" + modelName  // generated by the controller
		maasPolicyName = "policy-a"
	)

	tests := []struct {
		name            string
		annotations     map[string]string
		wantSpecChanged bool // true → controller should overwrite spec; false → must leave it alone
	}{
		{
			name:            "annotation absent: controller overwrites spec",
			annotations:     map[string]string{},
			wantSpecChanged: true,
		},
		{
			name:            "opendatahub.io/managed=false: controller skips update (opt-out)",
			annotations:     map[string]string{ManagedByODHOperator: "false"},
			wantSpecChanged: false,
		},
		{
			name:            "opendatahub.io/managed=true: controller overwrites spec",
			annotations:     map[string]string{ManagedByODHOperator: "true"},
			wantSpecChanged: true,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
			route := newHTTPRoute(httpRouteName, namespace)
			maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
			// Pre-populate the store with a generated AuthPolicy whose spec contains a
			// sentinel targetRef. After reconciliation we check whether it changed.
			existingAP := newPreexistingAuthPolicy(authPolicyName, namespace, modelName, tc.annotations)

			c := fake.NewClientBuilder().
				WithScheme(scheme).
				WithRESTMapper(testRESTMapper()).
				WithObjects(model, route, maasPolicy, existingAP).
				WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
				Build()

			r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
			req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
			if _, err := r.Reconcile(context.Background(), req); err != nil {
				t.Fatalf("Reconcile: unexpected error: %v", err)
			}

			got := &unstructured.Unstructured{}
			got.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
			if err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: namespace}, got); err != nil {
				t.Fatalf("Get AuthPolicy %q: %v", authPolicyName, err)
			}

			// The controller sets spec.targetRef.name to the HTTPRoute name on update.
			// A sentinel value means no update occurred.
			targetRefName, found, err := unstructured.NestedString(got.Object, "spec", "targetRef", "name")
			if err != nil || !found {
				t.Fatalf("spec.targetRef.name missing or invalid: found=%v err=%v", found, err)
			}
			if tc.wantSpecChanged {
				if targetRefName != httpRouteName {
					t.Errorf("spec.targetRef.name = %q: expected %q", targetRefName, httpRouteName)
				}
			} else if targetRefName != "sentinel-route" {
				t.Errorf("spec.targetRef.name = %q: expected sentinel %q (managed=false opt-out)", targetRefName, "sentinel-route")
			}
		})
	}
}

// TestMaaSAuthPolicyReconciler_DuplicateReconciliation verifies that reconciling
// multiple auth policies for the same model does not produce redundant AuthPolicy updates.
//
// When N auth policies reference the same model, each reconciliation builds the same
// aggregated AuthPolicy. The controller must skip the Update call when the content is
// identical to what already exists, otherwise each Update triggers a watch event that
// cascades into O(N²) reconciliations.
func TestMaaSAuthPolicyReconciler_DuplicateReconciliation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		httpRouteName  = "maas-model-" + modelName
		authPolicyName = "maas-auth-" + modelName
	)

	model := newMaaSModelRef(modelName, namespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, namespace)
	policyA := newMaaSAuthPolicy("policy-a", namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
	policyB := newMaaSAuthPolicy("policy-b", namespace, "team-b", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, policyA, policyB).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	ctx := context.Background()

	// Reconcile policy-a: creates the aggregated AuthPolicy (covering both policy-a and policy-b).
	reqA := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-a", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, reqA); err != nil {
		t.Fatalf("Reconcile policy-a: %v", err)
	}

	// Capture AuthPolicy ResourceVersion after first reconciliation.
	ap := &unstructured.Unstructured{}
	ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: authPolicyName, Namespace: namespace}, ap); err != nil {
		t.Fatalf("Get AuthPolicy after policy-a reconcile: %v", err)
	}
	rvAfterA := ap.GetResourceVersion()

	// Reconcile policy-b: both policies are still present, so the aggregated AuthPolicy
	// content is identical. The controller should detect this and skip the Update.
	reqB := ctrl.Request{NamespacedName: types.NamespacedName{Name: "policy-b", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, reqB); err != nil {
		t.Fatalf("Reconcile policy-b: %v", err)
	}

	if err := c.Get(ctx, types.NamespacedName{Name: authPolicyName, Namespace: namespace}, ap); err != nil {
		t.Fatalf("Get AuthPolicy after policy-b reconcile: %v", err)
	}
	rvAfterB := ap.GetResourceVersion()

	if rvAfterA != rvAfterB {
		t.Errorf("redundant AuthPolicy update: ResourceVersion changed from %s to %s; "+
			"reconciling policy-b should not update the AuthPolicy when content is identical to policy-a's reconciliation",
			rvAfterA, rvAfterB)
	}
}

// TestMaaSAuthPolicyReconciler_DeleteAnnotation verifies that the Reconcile deletion
// path respects the opt-out annotation: an AuthPolicy with opendatahub.io/managed=false
// must not be deleted when the parent MaaSAuthPolicy is removed.
func TestMaaSAuthPolicyReconciler_DeleteAnnotation(t *testing.T) {
	const (
		modelName      = "llm"
		namespace      = "default"
		authPolicyName = "maas-auth-" + modelName
		maasPolicyName = "policy-a"
	)

	tests := []struct {
		name        string
		annotations map[string]string
		wantDeleted bool
	}{
		{
			name:        "annotation absent: controller deletes",
			annotations: map[string]string{},
			wantDeleted: true,
		},
		{
			name:        "opendatahub.io/managed=true: controller deletes",
			annotations: map[string]string{ManagedByODHOperator: "true"},
			wantDeleted: true,
		},
		{
			name:        "opendatahub.io/managed=false: controller must not delete",
			annotations: map[string]string{ManagedByODHOperator: "false"},
			wantDeleted: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			existingAP := newPreexistingAuthPolicy(authPolicyName, namespace, modelName, tc.annotations)

			// Create MaaSAuthPolicy with finalizer so handleDeletion processes it.
			maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a", maasv1alpha1.ModelRef{Name: modelName, Namespace: namespace})
			maasPolicy.Finalizers = []string{maasAuthPolicyFinalizer}

			c := fake.NewClientBuilder().
				WithScheme(scheme).
				WithRESTMapper(testRESTMapper()).
				WithObjects(maasPolicy, existingAP).
				Build()

			// Simulate deletion: the fake client sets DeletionTimestamp while the
			// finalizer keeps the object in the store.
			if err := c.Delete(context.Background(), maasPolicy); err != nil {
				t.Fatalf("Delete MaaSAuthPolicy: %v", err)
			}

			r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
			req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}
			if _, err := r.Reconcile(context.Background(), req); err != nil {
				t.Fatalf("Reconcile: unexpected error: %v", err)
			}

			got := &unstructured.Unstructured{}
			got.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
			err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: namespace}, got)

			if tc.wantDeleted {
				if !apierrors.IsNotFound(err) {
					t.Errorf("expected AuthPolicy %q to be deleted, but it still exists", authPolicyName)
				}
			} else {
				if err != nil {
					t.Errorf("expected AuthPolicy %q to survive deletion (managed=false opt-out), but got: %v", authPolicyName, err)
				}
			}
		})
	}
}
// TestMaaSAuthPolicyReconciler_RemoveModelRef verifies that removing a modelRef from
// a MaaSAuthPolicy deletes the aggregated AuthPolicy for the removed model while
// keeping the AuthPolicy for the remaining model intact.
func TestMaaSAuthPolicyReconciler_RemoveModelRef(t *testing.T) {
	const (
		modelA         = "model-a"
		modelB         = "model-b"
		namespace      = "default"
		httpRouteA     = "maas-model-" + modelA
		httpRouteB     = "maas-model-" + modelB
		authPolicyA    = "maas-auth-" + modelA
		authPolicyB    = "maas-auth-" + modelB
		maasPolicyName = "policy-1"
	)

	modelRefA := newMaaSModelRef(modelA, namespace, "ExternalModel", modelA)
	modelRefB := newMaaSModelRef(modelB, namespace, "ExternalModel", modelB)
	routeA := newHTTPRoute(httpRouteA, namespace)
	routeB := newHTTPRoute(httpRouteB, namespace)

	maasPolicy := newMaaSAuthPolicy(maasPolicyName, namespace, "team-a",
		maasv1alpha1.ModelRef{Name: modelA, Namespace: namespace},
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(modelRefA, modelRefB, routeA, routeB, maasPolicy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	ctx := context.Background()
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: namespace}}

	if _, err := r.Reconcile(ctx, req); err != nil {
		t.Fatalf("Initial reconcile: %v", err)
	}

	// Both AuthPolicies should exist
	for _, name := range []string{authPolicyA, authPolicyB} {
		ap := &unstructured.Unstructured{}
		ap.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
		if err := c.Get(ctx, types.NamespacedName{Name: name, Namespace: namespace}, ap); err != nil {
			t.Fatalf("AuthPolicy %q not found after initial reconcile: %v", name, err)
		}
	}

	// Remove model B from the policy
	freshPolicy := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(ctx, types.NamespacedName{Name: maasPolicyName, Namespace: namespace}, freshPolicy); err != nil {
		t.Fatalf("Get MaaSAuthPolicy: %v", err)
	}
	freshPolicy.Spec.ModelRefs = []maasv1alpha1.ModelRef{{Name: modelA, Namespace: namespace}}
	if err := c.Update(ctx, freshPolicy); err != nil {
		t.Fatalf("Update MaaSAuthPolicy: %v", err)
	}

	if _, err := r.Reconcile(ctx, req); err != nil {
		t.Fatalf("Reconcile after removing modelRef: %v", err)
	}

	// AuthPolicy for model A should still exist
	apA := &unstructured.Unstructured{}
	apA.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: authPolicyA, Namespace: namespace}, apA); err != nil {
		t.Errorf("AuthPolicy for model A should still exist: %v", err)
	}

	// AuthPolicy for model B should be DELETED
	apB := &unstructured.Unstructured{}
	apB.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	err := c.Get(ctx, types.NamespacedName{Name: authPolicyB, Namespace: namespace}, apB)
	if !apierrors.IsNotFound(err) {
		t.Errorf("AuthPolicy for model B should be deleted after removing modelRef, but got: %v", err)
	}
}

// TestMaaSAuthPolicyReconciler_RemoveModelRef_Aggregation verifies that when one policy
// drops a model that another policy still references, the aggregated AuthPolicy is deleted
// (forcing a rebuild by the remaining policy) without affecting unrelated models.
func TestMaaSAuthPolicyReconciler_RemoveModelRef_Aggregation(t *testing.T) {
	const (
		modelA      = "model-a"
		modelB      = "model-b"
		namespace   = "default"
		httpRouteA  = "maas-model-" + modelA
		httpRouteB  = "maas-model-" + modelB
		authPolicyB = "maas-auth-" + modelB
	)

	modelRefA := newMaaSModelRef(modelA, namespace, "ExternalModel", modelA)
	modelRefB := newMaaSModelRef(modelB, namespace, "ExternalModel", modelB)
	routeA := newHTTPRoute(httpRouteA, namespace)
	routeB := newHTTPRoute(httpRouteB, namespace)

	// ap1 references [A, B], ap2 references [B]
	ap1 := newMaaSAuthPolicy("ap1", namespace, "team-1",
		maasv1alpha1.ModelRef{Name: modelA, Namespace: namespace},
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)
	ap2 := newMaaSAuthPolicy("ap2", namespace, "team-2",
		maasv1alpha1.ModelRef{Name: modelB, Namespace: namespace},
	)

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(modelRefA, modelRefB, routeA, routeB, ap1, ap2).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	ctx := context.Background()

	// Reconcile both policies to create aggregated AuthPolicies
	req1 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "ap1", Namespace: namespace}}
	req2 := ctrl.Request{NamespacedName: types.NamespacedName{Name: "ap2", Namespace: namespace}}
	if _, err := r.Reconcile(ctx, req1); err != nil {
		t.Fatalf("Reconcile ap1: %v", err)
	}
	if _, err := r.Reconcile(ctx, req2); err != nil {
		t.Fatalf("Reconcile ap2: %v", err)
	}

	// AuthPolicy for model B should exist with both policies contributing
	apB := &unstructured.Unstructured{}
	apB.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: authPolicyB, Namespace: namespace}, apB); err != nil {
		t.Fatalf("AuthPolicy for model B not found: %v", err)
	}

	// Remove model B from ap1 (ap2 still references it)
	freshAP1 := &maasv1alpha1.MaaSAuthPolicy{}
	if err := c.Get(ctx, types.NamespacedName{Name: "ap1", Namespace: namespace}, freshAP1); err != nil {
		t.Fatalf("Get ap1: %v", err)
	}
	freshAP1.Spec.ModelRefs = []maasv1alpha1.ModelRef{{Name: modelA, Namespace: namespace}}
	if err := c.Update(ctx, freshAP1); err != nil {
		t.Fatalf("Update ap1: %v", err)
	}

	// Reconcile ap1 → should delete stale AuthPolicy for model B
	if _, err := r.Reconcile(ctx, req1); err != nil {
		t.Fatalf("Reconcile ap1 after removing modelRef: %v", err)
	}

	// AuthPolicy for model B should be deleted (stale from ap1's perspective)
	apB = &unstructured.Unstructured{}
	apB.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	err := c.Get(ctx, types.NamespacedName{Name: authPolicyB, Namespace: namespace}, apB)
	if !apierrors.IsNotFound(err) {
		t.Fatalf("AuthPolicy for model B should be deleted after ap1 drops it, but got: %v", err)
	}

	// Reconcile ap2 → should recreate AuthPolicy for model B with only ap2's subjects
	if _, err := r.Reconcile(ctx, req2); err != nil {
		t.Fatalf("Reconcile ap2 after ap1 drop: %v", err)
	}

	apB = &unstructured.Unstructured{}
	apB.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(ctx, types.NamespacedName{Name: authPolicyB, Namespace: namespace}, apB); err != nil {
		t.Errorf("AuthPolicy for model B should be rebuilt by ap2: %v", err)
	}

	// Verify only ap2 is in the annotation (ap1 no longer contributes)
	ann := apB.GetAnnotations()["maas.opendatahub.io/auth-policies"]
	if ann != "ap2" {
		t.Errorf("AuthPolicy annotation = %q, want %q (only ap2 should contribute)", ann, "ap2")
	}
}

// TestMaaSAuthPolicyReconciler_MultiplePoliciesDeletion verifies that when multiple
// MaaSAuthPolicies reference the same model, deleting one does not delete the aggregated
// AuthPolicy, but deleting the last one does.
func TestMaaSAuthPolicyReconciler_MultiplePoliciesDeletion(t *testing.T) {
	const (
		modelName      = "shared-model"
		modelNamespace = "llm"
		httpRouteName  = "maas-model-" + modelName
		authPolicyName = "maas-auth-" + modelName
		policy1Name    = "policy-1"
		policy2Name    = "policy-2"
		policyNS       = "opendatahub"
	)

	// Create model and HTTPRoute
	model := &maasv1alpha1.MaaSModelRef{
		ObjectMeta: metav1.ObjectMeta{Name: modelName, Namespace: modelNamespace},
		Spec: maasv1alpha1.MaaSModelSpec{
			ModelRef: maasv1alpha1.ModelReference{Kind: "ExternalModel", Name: modelName},
		},
	}
	route := &gatewayapiv1.HTTPRoute{
		ObjectMeta: metav1.ObjectMeta{Name: httpRouteName, Namespace: modelNamespace},
	}

	// Create two MaaSAuthPolicies both referencing the same model
	policy1 := &maasv1alpha1.MaaSAuthPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:       policy1Name,
			Namespace:  policyNS,
			Finalizers: []string{maasAuthPolicyFinalizer},
		},
		Spec: maasv1alpha1.MaaSAuthPolicySpec{
			ModelRefs: []maasv1alpha1.ModelRef{{Name: modelName, Namespace: modelNamespace}},
			Subjects:  maasv1alpha1.SubjectSpec{Groups: []maasv1alpha1.GroupReference{{Name: "team-1"}}},
		},
	}
	policy2 := &maasv1alpha1.MaaSAuthPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:       policy2Name,
			Namespace:  policyNS,
			Finalizers: []string{maasAuthPolicyFinalizer},
		},
		Spec: maasv1alpha1.MaaSAuthPolicySpec{
			ModelRefs: []maasv1alpha1.ModelRef{{Name: modelName, Namespace: modelNamespace}},
			Subjects:  maasv1alpha1.SubjectSpec{Groups: []maasv1alpha1.GroupReference{{Name: "team-2"}}},
		},
	}

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, policy1, policy2).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}

	// Reconcile both policies to create the aggregated AuthPolicy
	req1 := ctrl.Request{NamespacedName: types.NamespacedName{Name: policy1Name, Namespace: policyNS}}
	if _, err := r.Reconcile(context.Background(), req1); err != nil {
		t.Fatalf("Reconcile policy1: %v", err)
	}
	req2 := ctrl.Request{NamespacedName: types.NamespacedName{Name: policy2Name, Namespace: policyNS}}
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy2: %v", err)
	}

	// Verify aggregated AuthPolicy was created
	authPolicy := &unstructured.Unstructured{}
	authPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: modelNamespace}, authPolicy); err != nil {
		t.Fatalf("AuthPolicy not found before deletion: %v", err)
	}

	// Delete policy1 (but policy2 still exists)
	if err := c.Delete(context.Background(), policy1); err != nil {
		t.Fatalf("Delete policy1: %v", err)
	}
	// Reconcile policy1 deletion - this will delete the aggregated AuthPolicy
	if _, err := r.Reconcile(context.Background(), req1); err != nil {
		t.Fatalf("Reconcile policy1 deletion: %v", err)
	}

	// Reconcile policy2 so it recreates the AuthPolicy without policy1's subjects
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy2 after policy1 deletion: %v", err)
	}

	// Aggregated AuthPolicy should exist again (rebuilt by policy2)
	authPolicy = &unstructured.Unstructured{}
	authPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: modelNamespace}, authPolicy); err != nil {
		t.Errorf("AuthPolicy should be rebuilt by policy2 after policy1 deletion: %v", err)
	}

	// Now delete policy2 (the last one)
	if err := c.Delete(context.Background(), policy2); err != nil {
		t.Fatalf("Delete policy2: %v", err)
	}
	if _, err := r.Reconcile(context.Background(), req2); err != nil {
		t.Fatalf("Reconcile policy2 deletion: %v", err)
	}

	// Aggregated AuthPolicy should NOW BE DELETED (no remaining parents)
	authPolicy = &unstructured.Unstructured{}
	authPolicy.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: modelNamespace}, authPolicy)
	if !apierrors.IsNotFound(err) {
		t.Errorf("AuthPolicy should be deleted after deleting last parent policy, but got error: %v", err)
	}
}

// TestMaaSAuthPolicyReconciler_SubscriptionCacheKey verifies that the generated AuthPolicy
// uses a composite cache key for subscription-info metadata that includes username, groups,
// requested subscription header, and model namespace/name.
//
// This prevents stale cached responses when:
// - A user switches subscriptions via X-MaaS-Subscription header within the cache TTL
// - Different models are accessed by the same user (cross-model cache collision)
//
// Regression test for RHOAIENG-54147.
func TestMaaSAuthPolicyReconciler_SubscriptionCacheKey(t *testing.T) {
	const (
		modelName      = "granite"
		modelNamespace = "models"
		httpRouteName  = "maas-model-" + modelName
		authPolicyName = "maas-auth-" + modelName
		maasPolicyName = "policy-cache"
	)

	model := newMaaSModelRef(modelName, modelNamespace, "ExternalModel", modelName)
	route := newHTTPRoute(httpRouteName, modelNamespace)
	maasPolicy := newMaaSAuthPolicy(maasPolicyName, modelNamespace, "team-cache",
		maasv1alpha1.ModelRef{Name: modelName, Namespace: modelNamespace})

	c := fake.NewClientBuilder().
		WithScheme(scheme).
		WithRESTMapper(testRESTMapper()).
		WithObjects(model, route, maasPolicy).
		WithStatusSubresource(&maasv1alpha1.MaaSAuthPolicy{}).
		Build()

	r := &MaaSAuthPolicyReconciler{Client: c, Scheme: scheme, MaaSAPINamespace: "maas-system"}
	req := ctrl.Request{NamespacedName: types.NamespacedName{Name: maasPolicyName, Namespace: modelNamespace}}
	if _, err := r.Reconcile(context.Background(), req); err != nil {
		t.Fatalf("Reconcile: unexpected error: %v", err)
	}

	// Fetch the generated AuthPolicy
	got := &unstructured.Unstructured{}
	got.SetGroupVersionKind(schema.GroupVersionKind{Group: "kuadrant.io", Version: "v1", Kind: "AuthPolicy"})
	if err := c.Get(context.Background(), types.NamespacedName{Name: authPolicyName, Namespace: modelNamespace}, got); err != nil {
		t.Fatalf("Get AuthPolicy %q: %v", authPolicyName, err)
	}

	// Extract the subscription-info cache key selector from the AuthPolicy spec
	cacheKeySelector, found, err := unstructured.NestedString(got.Object,
		"spec", "rules", "metadata", "subscription-info", "cache", "key", "selector")
	if err != nil || !found {
		t.Fatalf("subscription-info cache key selector not found: found=%v err=%v", found, err)
	}

	// Verify the cache key selector is a syntactically valid CEL expression
	env, err := cel.NewEnv()
	if err != nil {
		t.Fatalf("failed to create CEL environment: %v", err)
	}
	if _, issues := env.Parse(cacheKeySelector); issues != nil && issues.Err() != nil {
		t.Fatalf("cache key selector is not valid CEL: %v\nexpression: %s", issues.Err(), cacheKeySelector)
	}

	// Verify the cache key includes all required components
	tests := []struct {
		name   string
		substr string
		reason string
	}{
		{
			name:   "includes username",
			substr: "auth.metadata.apiKeyValidation.username",
			reason: "cache key must include username to distinguish different users",
		},
		{
			name:   "includes groups",
			substr: `auth.metadata.apiKeyValidation.groups.join(",")`,
			reason: "cache key must include groups to prevent collisions between users with different group memberships",
		},
		{
			name:   "includes X-MaaS-Subscription header",
			substr: `"x-maas-subscription" in request.headers`,
			reason: "cache key must include requested subscription to prevent stale results when switching subscriptions",
		},
		{
			name:   "includes model namespace/name",
			substr: modelNamespace + "/" + modelName,
			reason: "cache key must include model to prevent cross-model cache collisions",
		},
		{
			name:   "uses pipe delimiters",
			substr: `+ "|" +`,
			reason: "cache key components must be separated by pipe delimiters for unambiguous parsing",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if !strings.Contains(cacheKeySelector, tc.substr) {
				t.Errorf("cache key selector missing %q: %s\ngot: %s", tc.substr, tc.reason, cacheKeySelector)
			}
		})
	}

	// Verify the cache key selector is a syntactically valid CEL expression.
	// Authorino evaluates this string as CEL at runtime, so a syntax error here
	// would cause all subscription-info cache lookups to fail silently.
	t.Run("is valid CEL expression", func(t *testing.T) {
		env, err := cel.NewEnv()
		if err != nil {
			t.Fatalf("failed to create CEL environment: %v", err)
		}
		ast, issues := env.Parse(cacheKeySelector)
		if issues != nil && issues.Err() != nil {
			t.Errorf("cache key selector is not a valid CEL expression:\n  selector: %s\n  parse error: %v", cacheKeySelector, issues.Err())
		}
		if ast == nil {
			t.Errorf("CEL parse returned nil AST for selector: %s", cacheKeySelector)
		}
	})
}
