apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: maas-api-backend-tls
  namespace: openshift-ingress
spec:
  host: maas-api.maas-api.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 8443
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
