apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: maas-controller-configmap-write-role
  namespace: opendatahub
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "patch", "update"]
