name: Disconnected Readiness
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  check:
    uses: opendatahub-io/disconnected-readiness-scorer/.github/workflows/disconnected-readiness-check.yml@cc5acfcdaccc4d89c1de154c4c21d9cf5e350209 # v1
    with:
      rules: ""
